name: CI

# this is triggered on push to the repository
on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.4.0
      - name: Template Test
        uses: benjivesterby/update-sync-on-template-use@main
        with: 
          token: "${{ secrets.GH_PAT }}"
          org: "devnw"
          repo: "shared"
          sync_file: sync.yml
          # siging_key: "${{ secrets.GPG_KEY }}"